### ISSUE TITLE
[solved] any way to use with es6 import?

### ISSUE THREAD

**Issue by erickythierry** [ssnangua/sharp-gif#1]
I tried to import your lib in every possible way using js es6, but it doesn't work.
but if I use it as commonjs the lib works normally.

using `import * as GIF from "sharp-gif"` and running the example code, the script runs normally without errors but no file is generated. the script only generates some file when I use the commonjs `require(...)`

**any idea how I could use your lib in an ES6 project?**

**Comment by ssnangua** [comment]
> I tried to import your lib in every possible way using js es6, but it doesn't work. but if I use it as commonjs the lib works normally.
> 
> using `import * as GIF from "sharp-gif"` and running the example code, the script runs normally without errors but no file is generated. the script only generates some file when I use the commonjs `require(...)`
> 
> **any idea how I could use your lib in an ES6 project?**

Have you set `"type": "module"` in package.json? It works fine when I set it like this:

`package.json`
```json
{
    "type": "module"
}
```

`test.js`
```javascript
import sharp from "sharp";
import GIF from "sharp-gif";

(async () => {
  const image = await GIF.createGif()
    .addFrame([
      sharp("./frames/0000.png"),
      sharp("./frames/0001.png"),
      sharp("./frames/0002.png"),
    ])
    .toSharp();
  image.toFile("./frames.gif");
})();
```

Or you can use something like babel or webpack which will transpile es6 code to commonJS.

**Comment by erickythierry** [comment]
> > I tried to import your lib in every possible way using js es6, but it doesn't work. but if I use it as commonjs the lib works normally.
> > using `import * as GIF from "sharp-gif"` and running the example code, the script runs normally without errors but no file is generated. the script only generates some file when I use the commonjs `require(...)`
> > **any idea how I could use your lib in an ES6 project?**
> 
> Have you set `"type": "module"` in package.json? It works fine when I set it like this:
> 
> `package.json`
> 
> ```json
> {
>     "type": "module"
> }
> ```
> 
> `test.js`
> 
> ```js
> import sharp from "sharp";
> import GIF from "sharp-gif";
> 
> (async () => {
>   const image = await GIF.createGif()
>     .addFrame([
>       sharp("./frames/0000.png"),
>       sharp("./frames/0001.png"),
>       sharp("./frames/0002.png"),
>     ])
>     .toSharp();
>   image.toFile("./frames.gif");
> })();
> ```
> 
> Or you can use something like babel or webpack which will transpile es6 code to commonJS.

Thanks for the answer.
I apologize for this inconvenience.
I ended up finding out that the problem was another lib that I was using together. I don't know why, but if I import the other lib, this one doesn't generate the final file, I couldn't come up with a solution to work both together, but definitely the problem is not with your lib. thanks for listening
